# Generated by Django 2.2.6 on 2019-10-17 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='유저명')),
                ('is_active', models.BooleanField(default=True, verbose_name='상태')),
                ('is_admin', models.BooleanField(default=False, editable=False, verbose_name='관리자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
